import {
  mockUsers,
  mockAdmins,
  mockSellers,
  mockCategories,
  mockOrders,
  mockProducts,
  mockCommunities,
  mockReviews,
  mockTransactions,
  mockLedger,
  mockGatewayLogs,
  mockShipments,
  mockCarriers,
  mockDeliveryZones,
  mockTickets,
  mockAuditLogs,
  mockPromotions,
  mockCommissionSettings,
  mockCoupons,
  mockRevenueMetrics,
  mockNotificationTemplates,
  mockNotificationHistory,
  mockReportedProducts,
  mockReportedMessages,
  mockReportedComments,
  mockFeedPosts,
  mockBlockedUsers,
  mockAddressBook,
  mockPaymentMethods,
  mockLiveStreams,
  mockReels,
  mockStories,
  mockHashtags,
  mockBundles as mockBundleRows,
  mockFoodHub as mockFoodHubRows,
  mockBroadcasts,
  mockBookings,
  mockLoyaltyUsers,
  mockDisputes,
  mockAuctionRows,
} from "@/services/mock-data";

export const CLIENT_MOCK_ROWS: Record<string, unknown[]> = {
  users: mockUsers,
  admins: mockAdmins,
  sellers: mockSellers,
  categories: mockCategories,
  products: mockProducts,
  orders: mockOrders,
  communities: mockCommunities,
  reviews: mockReviews,
  transactions: mockTransactions,
  ledger: mockLedger,
  "gateway-logs": mockGatewayLogs,
  shipments: mockShipments,
  carriers: mockCarriers,
  "delivery-zones": mockDeliveryZones,
  tickets: mockTickets,
  "audit-logs": mockAuditLogs,
  promotions: mockPromotions,
  commission: [mockCommissionSettings],
  coupons: mockCoupons,
  "revenue-metrics": [mockRevenueMetrics],
  "notification-templates": mockNotificationTemplates,
  "notification-history": mockNotificationHistory,
  "reported-products": mockReportedProducts,
  "reported-messages": mockReportedMessages,
  "reported-comments": mockReportedComments,
  posts: mockFeedPosts,
  blocked: mockBlockedUsers,
  "address-book": mockAddressBook,
  "payment-methods": mockPaymentMethods,
  live: mockLiveStreams,
  reels: mockReels,
  stories: mockStories,
  hashtags: mockHashtags,
  bundles: mockBundleRows,
  "food-hub": mockFoodHubRows,
  broadcasts: mockBroadcasts,
  bookings: mockBookings,
  loyalty: mockLoyaltyUsers,
  disputes: mockDisputes,
  auctions: mockAuctionRows,
};

export function clientMockRows(resource: string): unknown[] {
  return CLIENT_MOCK_ROWS[resource] ?? [];
}