/**
 * HEX COLOR → THEME TOKEN MAPPING
 * Maps every unique hex color found in the Figma screens to its
 * corresponding theme.ts token.
 * 
 * Generated by scanning all 33 JSON files + figma_execute plugin extraction.
 * Frequency: how many times this hex appears across all screens.
 * 
 * For colors NOT in theme.ts, maps to the closest theme token.
 */

export const HEX_TO_TOKEN: Record<string, { token: string; hex: string; frequency: number }> = {
  // === HIGH FREQUENCY (appear 10+ times) ===
  '#ffffff':   { token: 'colors.surfaceContainerLowest', hex: '#ffffff',  frequency: 80 },
  '#fcf8ff':   { token: 'colors.surface',                hex: '#fcf8ff',  frequency: 51 },
  '#4343d5':   { token: 'colors.primary',                hex: '#4343d5',  frequency: 33 },
  '#f5f2ff':   { token: 'colors.surfaceContainerLow',    hex: '#f5f2ff',  frequency: 18 },
  '#464555':   { token: 'colors.textSecondary',          hex: '#464555',  frequency: 15 },
  '#5d5fef':   { token: 'colors.primaryContainer',       hex: '#5d5fef',  frequency: 14 },
  '#1a1a2e':   { token: 'colors.textPrimary',            hex: '#1a1a2e',  frequency: 10 },

  // === MEDIUM FREQUENCY (4-9 times) ===
  '#dedfe5':   { token: 'colors.secondaryContainer',     hex: '#dedfe5',  frequency: 8 },
  '#434343':   { token: 'colors.textPrimary',            hex: '#1a1a2e',  frequency: 8 },  // Figma-specific dark, map to textPrimary
  '#5c5e63':   { token: 'colors.textSecondary',          hex: '#5c5e63',  frequency: 8 },
  '#fcfcfd':   { token: 'colors.surfaceContainerLowest', hex: '#ffffff',  frequency: 7 },  // Near-white, map to surface
  '#efecff':   { token: 'colors.surfaceContainer',       hex: '#efecff',  frequency: 7 },
  '#e8e8e9':   { token: 'colors.secondaryContainer',     hex: '#dedfe5',  frequency: 4 },  // Near-secondary
  '#010101':   { token: 'colors.textPrimary',            hex: '#1a1a2e',  frequency: 4 },  // Near-black
  '#d5d5d6':   { token: 'colors.outlineVariant',         hex: '#c7c4d7',  frequency: 4 },  // Near-outline
  '#000000':   { token: 'colors.textPrimary',            hex: '#1a1a2e',  frequency: 4 },

  // === LOW FREQUENCY (1-2 times) ===
  '#ba1a1a':   { token: 'colors.error',                  hex: '#ba1a1a',  frequency: 2 },
  '#fafafb':   { token: 'colors.surfaceContainerLowest', hex: '#ffffff',  frequency: 2 },
  '#e2e0fc':   { token: 'colors.surfaceVariant',         hex: '#e2e0fc',  frequency: 2 },
  '#50519b':   { token: 'colors.tertiary',               hex: '#50519b',  frequency: 1 },
  '#c1c1ff':   { token: 'colors.inversePrimary',         hex: '#c1c1ff',  frequency: 1 },
  '#ffdad6':   { token: 'colors.errorContainer',         hex: '#ffdad6',  frequency: 1 },
  '#22c55e':   { token: 'colors.primary',                hex: '#4343d5',  frequency: 1 },  // Green (success), map to primary

  // === SINGLE-USE (1 time) ===
  '#fffbeb':   { token: 'colors.surfaceContainerLow',    hex: '#f5f2ff',  frequency: 1 }, // Warm bg
  '#ecfdf5':   { token: 'colors.surfaceContainerLow',    hex: '#f5f2ff',  frequency: 1 }, // Mint bg
  '#454545':   { token: 'colors.textSecondary',          hex: '#5c5e63',  frequency: 1 },
  '#f5f3ff':   { token: 'colors.surfaceContainerLow',    hex: '#f5f2ff',  frequency: 1 },
  '#e5e5e6':   { token: 'colors.secondaryContainer',     hex: '#dedfe5',  frequency: 1 },
  '#fdf2f8':   { token: 'colors.surface',                hex: '#fcf8ff',  frequency: 1 }, // Pink bg
  '#eff6ff':   { token: 'colors.surface',                hex: '#fcf8ff',  frequency: 1 }, // Blue bg
  '#fff1f2':   { token: 'colors.surface',                hex: '#fcf8ff',  frequency: 1 }, // Rose bg
  '#eef2ff':   { token: 'colors.surfaceContainerLow',    hex: '#f5f2ff',  frequency: 1 }, // Indigo bg
  '#f0f9ff':   { token: 'colors.surface',                hex: '#fcf8ff',  frequency: 1 }, // Sky bg
  '#f8fafc':   { token: 'colors.surface',                hex: '#fcf8ff',  frequency: 1 }, // Slate bg
  '#f5f5f6':   { token: 'colors.surfaceContainerLow',    hex: '#f5f2ff',  frequency: 1 },
  '#faf5ff':   { token: 'colors.surface',                hex: '#fcf8ff',  frequency: 1 }, // Purple bg
  '#dededf':   { token: 'colors.secondaryContainer',     hex: '#dedfe5',  frequency: 1 },
  '#fafaf9':   { token: 'colors.surfaceContainerLowest', hex: '#ffffff',  frequency: 1 },
  '#464646':   { token: 'colors.textSecondary',          hex: '#5c5e63',  frequency: 1 },
  '#f0fdf4':   { token: 'colors.surface',                hex: '#fcf8ff',  frequency: 1 }, // Green bg
  '#fff7ed':   { token: 'colors.surface',                hex: '#fcf8ff',  frequency: 1 }, // Orange bg
  '#fef2f2':   { token: 'colors.surfaceContainerLow',    hex: '#f5f2ff',  frequency: 1 }, // Red bg
  '#dfdfe0':   { token: 'colors.secondaryContainer',     hex: '#dedfe5',  frequency: 1 },
  '#ecfeff':   { token: 'colors.surface',                hex: '#fcf8ff',  frequency: 1 }, // Cyan bg
  '#636363':   { token: 'colors.textTertiary',           hex: '#767586',  frequency: 1 },
  '#6b7280':   { token: 'colors.textTertiary',           hex: '#767586',  frequency: 2 },
  '#606060':   { token: 'colors.textTertiary',           hex: '#767586',  frequency: 1 },
  '#faf7ff':   { token: 'colors.onPrimaryContainer',     hex: '#faf7ff',  frequency: 1 }, // Text on primary bg
};

/**
 * Helper: get the closest theme token for any hex color.
 * Returns the token name or 'colors.primary' as fallback.
 */
export function hexToToken(hex: string): string {
  const normalized = hex.toLowerCase();
  if (HEX_TO_TOKEN[normalized]) {
    return HEX_TO_TOKEN[normalized].token;
  }
  // Try matching rgba format
  if (normalized.startsWith('rgba')) {
    return 'colors.overlay'; // Best generic match
  }
  return 'colors.primary'; // Fallback
}
